name: publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: wasm32-unknown-unknown

      - uses: cargo-bins/cargo-binstall@main
      - run: cargo binstall wasm-bindgen-cli

      - run: cargo build --release --target wasm32-unknown-unknown
      - run: wasm-bindgen --no-typescript --target web --out-dir ./out --out-name "bevy-space-invaders" ./target/wasm32-unknown-unknown/release/bevy-space-invaders.wasm

      - run: cp -r ./assets ./out
      - run: cp ./index.html ./out
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
